"""
Conversational AI Chat & RAG Service with Citations, Confidence Scoring,
RAG Evaluation Metrics, LangSmith Tracing, and Advanced Retrieval.

Pipeline stages:
  1. Step-Back Prompting   — generates abstract query for broader recall
  2. Query Expansion       — 3 LLM query variants for coverage
  3. Hybrid Search + RRF   — Qdrant semantic + Postgres FTS fused
  4. Parent-Document Expand — child chunks replaced by richer parents
  5. LLM Reranking         — Gemini-scored relevance sorting
  6. Contextual Compression — strips noise from low-score chunks
  7. Agentic Loop (ReAct)  — LLM tool-calls for follow-up retrieval
  8. Final Generation      — structured JSON with citations
  9. RAGAS Eval (async)    — fire-and-forget faithfulness/relevancy scoring
  10. LangSmith Tracing    — full pipeline traced with child spans
"""

import uuid
import time
import logging
import re
import asyncio
import math
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field, asdict
from pydantic import BaseModel, Field
from google import genai
from google.genai import types

from app.config import settings
from app.services.search import hybrid_search


class RerankScore(BaseModel):
    """Relevance score for a candidate document."""
    index: int = Field(description="The index of the candidate document, starting at 0.")
    relevance_score: float = Field(description="A score between 0.0 (completely irrelevant) and 1.0 (highly relevant).")


class RerankResponse(BaseModel):
    """Structured response for reranking."""
    scores: List[RerankScore] = Field(description="List of relevance scores for each candidate document.")


logger = logging.getLogger(__name__)


class ChatCitation(BaseModel):
    """Citation mapping a statement back to a source node in the Feature Intelligence Graph."""
    key: int = Field(description="The numeric citation key, e.g., 1 (for [1]).")
    node_id: str = Field(description="The UUID string of the cited node.")
    node_type: str = Field(description="The type of node (e.g. requirement, decision, event).")
    title: str = Field(description="The title or brief summary of the node.")
    url: Optional[str] = Field(None, description="External URL if available.")
    snippet: Optional[str] = Field(None, description="A brief matching text snippet from the node content.")


@dataclass
class RAGMetrics:
    """Evaluation metrics for a single RAG pipeline invocation."""
    # --- Latency (seconds) ---
    total_latency_s: float = 0.0
    query_expansion_latency_s: float = 0.0
    retrieval_latency_s: float = 0.0
    reranking_latency_s: float = 0.0
    agentic_loop_latency_s: float = 0.0
    generation_latency_s: float = 0.0

    # --- Retrieval Quality ---
    expanded_query_count: int = 0
    step_back_query_used: bool = False
    total_candidates_retrieved: int = 0
    unique_candidates_after_merge: int = 0
    parent_documents_expanded: int = 0
    candidates_after_reranking: int = 0
    contextual_compression_applied: int = 0
    rerank_scores: List[float] = field(default_factory=list)
    rerank_mean_score: float = 0.0

    # --- Lightweight Retrieval Evaluation (token-overlap heuristic) ---
    retrieval_eval_precision_at_k: float = 0.0
    retrieval_eval_recall_at_k: float = 0.0
    retrieval_eval_hit_rate_at_k: float = 0.0
    retrieval_eval_mrr: float = 0.0
    retrieval_eval_ndcg: float = 0.0
    retrieval_eval_relevant_count: int = 0

    # --- RAGAS Evaluation (LLM-as-Judge, async fire-and-forget) ---
    ragas_faithfulness: float = 0.0
    ragas_answer_relevancy: float = 0.0
    ragas_context_precision: float = 0.0
    ragas_context_recall: float = 0.0
    ragas_context_entity_recall: float = 0.0
    ragas_score: float = 0.0
    ragas_evaluated: bool = False
    ragas_error: Optional[str] = None

    # --- LangSmith ---
    langsmith_trace_id: Optional[str] = None

    # --- Agentic ---
    agentic_tool_calls: int = 0
    agentic_loop_iterations: int = 0

    # --- Generation Quality ---
    confidence_score: float = 0.0
    citation_count: int = 0
    context_sources_used: int = 0

    # --- Faithfulness Proxy ---
    answer_length_chars: int = 0
    context_length_chars: int = 0
    context_utilization_ratio: float = 0.0


class ChatResponse(BaseModel):
    """The structured, validated response generated by the conversational AI agent."""
    answer: str = Field(description="The rich markdown response. Must cite sources inline using format [1], [2], matching the keys in the citations list.")
    confidence_score: float = Field(description="A confidence score between 0.0 and 1.0 reflecting factual alignment with the retrieved context.")
    citations: List[ChatCitation] = Field(description="List of exact nodes cited in the answer.")


def evaluate_retrieval_results(query: str, candidates: List[Any], top_k: int = 5) -> Dict[str, Any]:
    """Compute lightweight retrieval evaluation metrics from query/doc token overlap."""
    if not candidates:
        return {
            "precision_at_k": 0.0,
            "recall_at_k": 0.0,
            "hit_rate_at_k": 0.0,
            "mrr": 0.0,
            "ndcg": 0.0,
            "relevant_count": 0,
        }

    query_terms = set(re.findall(r"[a-zA-Z0-9_]+", query.lower()))

    def is_relevant(cand: Any) -> int:
        text = f"{getattr(cand, 'title', '')} {getattr(cand, 'content', '')}".lower()
        cand_terms = set(re.findall(r"[a-zA-Z0-9_]+", text))
        overlap = len(query_terms.intersection(cand_terms))
        return 1 if overlap >= 2 or (overlap == 1 and len(query_terms) <= 2) else 0

    top_candidates = candidates[:top_k]
    labels = [is_relevant(cand) for cand in top_candidates]
    relevant_count = sum(labels)
    total_relevant = sum(is_relevant(cand) for cand in candidates)

    precision_at_k = relevant_count / max(len(top_candidates), 1)
    recall_at_k = relevant_count / max(total_relevant, 1)
    hit_rate_at_k = 1.0 if relevant_count > 0 else 0.0

    mrr = 0.0
    for rank, label in enumerate(labels, start=1):
        if label:
            mrr = 1.0 / rank
            break

    dcg = sum(label / math.log2(rank + 1) for rank, label in enumerate(labels, start=1))
    ideal_labels = sorted(labels, reverse=True)
    idcg = sum(label / math.log2(rank + 1) for rank, label in enumerate(ideal_labels, start=1))
    ndcg = dcg / idcg if idcg else 0.0

    return {
        "precision_at_k": round(precision_at_k, 4),
        "recall_at_k": round(recall_at_k, 4),
        "hit_rate_at_k": round(hit_rate_at_k, 4),
        "mrr": round(mrr, 4),
        "ndcg": round(ndcg, 4),
        "relevant_count": relevant_count,
    }


# In-memory session store (session_id -> list of message dicts)
# Each message dict has: {"role": "user" | "model", "content": str}
chat_sessions: Dict[str, List[Dict[str, str]]] = {}


def get_or_create_session(session_id: str) -> List[Dict[str, str]]:
    """Retrieve or create a conversational history session."""
    if session_id not in chat_sessions:
        chat_sessions[session_id] = []
    return chat_sessions[session_id]


async def generate_content_with_retry(client, model, contents, config=None, retries=4, initial_delay=3.0):
    """Call Gemini generate_content asynchronously with exponential backoff on 429/rate-limits."""
    delay = initial_delay
    for attempt in range(retries):
        try:
            return await client.aio.models.generate_content(
                model=model,
                contents=contents,
                config=config
            )
        except Exception as e:
            err_msg = str(e)
            is_transient = any(term in err_msg for term in ["429", "503", "RESOURCE_EXHAUSTED", "Quota exceeded", "Rate limit", "UNAVAILABLE", "high demand", "temporary"])
            if is_transient and attempt < retries - 1:
                logger.warning(f"Gemini API transient error hit (attempt {attempt + 1}/{retries}). Retrying in {delay}s... Error: {e}")
                await asyncio.sleep(delay)
                delay *= 2.0
            else:
                raise e


async def expand_query_via_llm(query: str, client: genai.Client, model: str) -> List[str]:
    """Generate 3 alternative search queries representing different facets or synonyms."""
    prompt = (
        f"You are a search query expansion assistant.\n"
        f"Generate 3 alternative versions of the following search query to improve retrieval coverage in a vector database and database text search.\n"
        f"Keep the generated queries concise and focused on key search terms.\n"
        f"Output ONLY the queries, one per line. Do not number them or add preamble.\n\n"
        f"Query: {query}"
    )
    try:
        response = await generate_content_with_retry(
            client=client,
            model=model,
            contents=prompt,
        )
        expanded = [line.strip() for line in response.text.split("\n") if line.strip()]
        cleaned = []
        for q in expanded:
            # Clean up bullet points, numbers, quotes
            q_clean = re.sub(r'^(\d+[\.\)]|\-|\*)\s*', '', q).strip()
            q_clean = q_clean.strip('"\'')
            if q_clean:
                cleaned.append(q_clean)
        return cleaned[:3]
    except Exception as e:
        logger.warning(f"Query expansion failed: {e}")
        return []


async def rerank_results_via_llm(
    query: str,
    candidates: List[Any],
    client: genai.Client,
    model: str,
    top_k: int = 5
) -> List[Any]:
    """Use Gemini to rerank candidates based on semantic relevance to the query."""
    if not candidates:
        return [], []

    if len(candidates) <= 1:
        return candidates[:top_k], [1.0] * len(candidates[:top_k])

    candidate_texts = []
    for idx, cand in enumerate(candidates):
        snippet = f"ID: {idx}\nType: {cand.node_type}\nTitle: {cand.title or 'Untitled'}\nContent: {cand.content[:500]}"
        candidate_texts.append(snippet)

    candidates_formatted = "\n\n".join(candidate_texts)

    prompt = (
        f"You are an expert search reranker assistant.\n"
        f"Given the User Query and a list of candidate documents below, evaluate the relevance of each candidate to the query.\n"
        f"For each candidate, assign a relevance_score between 0.0 (irrelevant) and 1.0 (highly relevant) based on how well it answers or provides context for the query.\n\n"
        f"User Query: {query}\n\n"
        f"--- CANDIDATE DOCUMENTS ---\n"
        f"{candidates_formatted}\n\n"
        f"Generate a JSON response matching the specified schema."
    )

    try:
        response = await generate_content_with_retry(
            client=client,
            model=model,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=RerankResponse,
                temperature=0.0
            )
        )
        res_data = RerankResponse.model_validate_json(response.text)

        # Map scores back to candidates
        scored_candidates = []
        scores_map = {item.index: item.relevance_score for item in res_data.scores}

        for idx, cand in enumerate(candidates):
            score = scores_map.get(idx, 0.0)
            scored_candidates.append((cand, score))

        # Sort by score descending
        scored_candidates.sort(key=lambda x: x[1], reverse=True)
        top = scored_candidates[:top_k]
        return [cand for cand, _ in top], [score for _, score in top]
    except Exception as e:
        logger.warning(f"Reranking failed: {e}. Falling back to original order.")
        return candidates[:top_k], []


def add_results_to_citation_map(
    results: List[Any],
    citation_map: Dict[str, Dict[str, Any]],
    context_blocks: List[str]
):
    """Add search results to global citation map and format context blocks."""
    for res in results:
        node_id_str = str(res.node_id)
        # Avoid duplicating the same node
        existing_key = None
        for key, val in citation_map.items():
            if val["node_id"] == node_id_str:
                existing_key = key
                break

        if existing_key:
            continue

        ref_key = len(citation_map) + 1
        ref_key_str = str(ref_key)

        context_blocks.append(
            f"--- SOURCE [{ref_key}] ---\n"
            f"Node ID: {node_id_str}\n"
            f"Type: {res.node_type}\n"
            f"Title: {res.title or 'Untitled'}\n"
            f"Content: {res.content}\n"
            f"Metadata: {res.metadata or {}}\n"
            f"Graph Relationships: {res.graph_context or {}}\n"
        )

        citation_map[ref_key_str] = {
            "key": ref_key,
            "node_id": node_id_str,
            "node_type": res.node_type,
            "title": res.title or "Untitled",
            "url": res.metadata.get("url") if res.metadata else None,
            "snippet": res.content[:200] + "..." if len(res.content) > 200 else res.content
        }


async def retrieve_and_generate(
    db,  # Unused — we open a fresh session internally
    query: str,
    project_id: uuid.UUID,
    session_id: Optional[str] = None,
    limit: int = 5
) -> tuple[ChatResponse, RAGMetrics]:
    """
    Executes the full advanced RAG pipeline:
      1. Step-Back Prompting + Query Expansion for broad recall
      2. Multi-query Hybrid Search (Qdrant + Postgres RRF)
      3. Parent-Document Retrieval (small-to-big)
      4. LLM Reranking (Gemini cross-encoder)
      5. Contextual Compression (noise reduction)
      6. Agentic Loop (ReAct tool calls)
      7. Final JSON Generation with citations
      8. RAGAS Evaluation (fire-and-forget, async)
      9. LangSmith end-to-end tracing

    Returns (ChatResponse, RAGMetrics).
    """
    from app.services.tracing import pipeline_trace
    from app.services.advanced_retrieval import (
        generate_step_back_query,
        apply_contextual_compression,
        expand_to_parent_documents,
    )
    from app.services.evaluation import compute_ragas_metrics, RAGASMetrics

    pipeline_start = time.perf_counter()
    metrics = RAGMetrics()

    # Initialize Gemini Client
    api_key = settings.gemini_api_key
    client = genai.Client(api_key=api_key)
    model_name = settings.llm_model

    from app.database import async_session

    async with pipeline_trace(
        query=query,
        project_id=str(project_id),
        session_id=session_id,
    ) as trace:

        async with async_session() as db:

            # ── 1. Step-Back Prompting + Query Expansion ─────────────────
            t0 = time.perf_counter()
            async with trace.span("query_preparation", inputs={"query": query}):
                # Step-back: generate a more abstract version of the query
                step_back_q = await generate_step_back_query(query, client, model_name)
                metrics.step_back_query_used = step_back_q is not None

                # Standard query expansion: 3 paraphrase variants
                expanded_queries = await expand_query_via_llm(query, client, model_name)
                metrics.expanded_query_count = len(expanded_queries)

            metrics.query_expansion_latency_s = round(time.perf_counter() - t0, 4)
            logger.info(
                f"[RAG] Query prep: {metrics.query_expansion_latency_s}s | "
                f"StepBack={'yes' if step_back_q else 'no'} | "
                f"{len(expanded_queries)} expansion variants"
            )

            # ── 2. Hybrid Retrieval (multi-query) ────────────────────────
            t0 = time.perf_counter()
            search_limit = max(limit * 3, 15)
            all_search_results = []

            # Build query list: original + step-back + expanded variants
            query_list = [query]
            if step_back_q:
                query_list.append(step_back_q)
            query_list.extend(expanded_queries)

            async with trace.span("retrieval", inputs={"query_count": len(query_list)}):
                for q in query_list:
                    res_list = await hybrid_search(db, q, project_id, limit=search_limit)
                    all_search_results.append(res_list)

            total_candidates = sum(len(r) for r in all_search_results)
            metrics.total_candidates_retrieved = total_candidates

            # Round-robin interleave to prioritise diversity
            seen_nodes = set()
            merged_results = []
            max_len = max(len(r) for r in all_search_results) if all_search_results else 0
            for idx in range(max_len):
                for res_list in all_search_results:
                    if idx < len(res_list):
                        res = res_list[idx]
                        if res.node_id not in seen_nodes:
                            seen_nodes.add(res.node_id)
                            merged_results.append(res)

            metrics.unique_candidates_after_merge = len(merged_results)
            metrics.retrieval_latency_s = round(time.perf_counter() - t0, 4)
            logger.info(
                f"[RAG] Retrieval: {metrics.retrieval_latency_s}s | "
                f"{total_candidates} raw → {len(merged_results)} unique"
            )

            # ── 3. Parent-Document Retrieval ──────────────────────────────
            async with trace.span("parent_document_expansion"):
                merged_results = await expand_to_parent_documents(db, merged_results)

            # Count expansions (nodes with parent_document flag)
            metrics.parent_documents_expanded = sum(
                1 for r in merged_results
                if (r.metadata or {}).get("parent_document", False)
            )

            # ── 4. Lightweight Retrieval Eval (heuristic) ─────────────────
            retrieval_eval = evaluate_retrieval_results(query, merged_results, top_k=limit)
            metrics.retrieval_eval_precision_at_k = retrieval_eval["precision_at_k"]
            metrics.retrieval_eval_recall_at_k = retrieval_eval["recall_at_k"]
            metrics.retrieval_eval_hit_rate_at_k = retrieval_eval["hit_rate_at_k"]
            metrics.retrieval_eval_mrr = retrieval_eval["mrr"]
            metrics.retrieval_eval_ndcg = retrieval_eval["ndcg"]
            metrics.retrieval_eval_relevant_count = retrieval_eval["relevant_count"]
            logger.info(
                f"[RAG Eval] P@{limit}={metrics.retrieval_eval_precision_at_k} | "
                f"R@{limit}={metrics.retrieval_eval_recall_at_k} | "
                f"MRR={metrics.retrieval_eval_mrr} | nDCG={metrics.retrieval_eval_ndcg}"
            )

            # ── 5. LLM Reranking ──────────────────────────────────────────
            t0 = time.perf_counter()
            async with trace.span("reranking", inputs={"candidates": len(merged_results)}):
                reranked_results, rerank_scores = await rerank_results_via_llm(
                    query,
                    merged_results,
                    client,
                    model_name,
                    top_k=limit * 2  # Keep 2x limit before compression
                )
            metrics.reranking_latency_s = round(time.perf_counter() - t0, 4)
            metrics.candidates_after_reranking = len(reranked_results)
            metrics.rerank_scores = [round(s, 4) for s in rerank_scores]
            metrics.rerank_mean_score = round(sum(rerank_scores) / len(rerank_scores), 4) if rerank_scores else 0.0
            logger.info(
                f"[RAG] Reranking: {metrics.reranking_latency_s}s | "
                f"top scores={metrics.rerank_scores[:5]}"
            )

            # ── 6. Contextual Compression ─────────────────────────────────
            async with trace.span("contextual_compression"):
                reranked_results, compressed_count = await apply_contextual_compression(
                    query=query,
                    candidates=reranked_results,
                    rerank_scores=rerank_scores,
                    client=client,
                    model=model_name,
                    threshold=settings.contextual_compression_threshold,
                )
            metrics.contextual_compression_applied = compressed_count

            # Trim to final limit after compression
            reranked_results = reranked_results[:limit]

            # ── 7. Build Citation Map & Context Blocks ────────────────────
            citation_map: Dict[str, Dict[str, Any]] = {}
            context_blocks: List[str] = []
            add_results_to_citation_map(reranked_results, citation_map, context_blocks)

            # ── 8. Conversation History ───────────────────────────────────
            actual_session_id = session_id or str(uuid.uuid4())
            history = get_or_create_session(actual_session_id)

            history_str = ""
            for turn in history:
                history_str += f"{turn['role'].capitalize()}: {turn['content']}\n"

            # ── 9. Agentic Tool Use Loop (ReAct) ──────────────────────────
            search_tool_declaration = types.FunctionDeclaration(
                name="search_workspace",
                description="Search the project workspace database for additional requirements, decisions, events, features, or stakeholders.",
                parameters=types.Schema(
                    type=types.Type.OBJECT,
                    properties={
                        "query": types.Schema(
                            type=types.Type.STRING,
                            description="The search term or query string to look up."
                        )
                    },
                    required=["query"]
                )
            )
            tools = [types.Tool(function_declarations=[search_tool_declaration])]

            system_instruction = (
                "You are Axis AI, a premium software engineering alignment assistant.\n"
                "Your objective is to provide extremely accurate, well-reasoned answers to help teams understand their requirements, decisions, stakeholder actions, and development event logs.\n\n"
                "Instructions:\n"
                "1. Answer the User Query using the provided SOURCE blocks.\n"
                "2. You have access to a tool 'search_workspace' to query for additional information if needed.\n"
                "3. You MUST cite your statements inline using exact keys like [1], [2], etc., matching the respective SOURCE entry.\n"
                "4. Only cite facts that are directly supported by the sources. Do not invent citations or make claims without source evidence.\n"
                "5. If the sources do not contain enough information to answer, explain clearly what is missing and state that you cannot find the full answer."
            )

            formatted_context = "\n\n".join(context_blocks)
            initial_user_prompt = (
                f"{system_instruction}\n"
                f"--- CONTEXT RESOURCES ---\n"
                f"{formatted_context}\n\n"
                f"--- CONVERSATION HISTORY ---\n"
                f"{history_str}\n"
                f"User Query: {query}\n\n"
                f"Answer the query using the tools or output your response."
            )

            messages = [
                types.Content(
                    role="user",
                    parts=[types.Part.from_text(text=initial_user_prompt)]
                )
            ]

            t0 = time.perf_counter()
            loop_count = 0
            max_loops = 2
            total_tool_calls = 0

            async with trace.span("agentic_loop"):
                while loop_count < max_loops:
                    try:
                        response = await generate_content_with_retry(
                            client=client,
                            model=model_name,
                            contents=messages,
                            config=types.GenerateContentConfig(
                                tools=tools,
                                temperature=0.2
                            )
                        )
                    except Exception as e:
                        logger.exception(f"Gemini agent loop call failed: {e}")
                        break

                    function_calls = response.function_calls
                    if not function_calls:
                        break

                    messages.append(response.candidates[0].content)

                    tool_parts = []
                    for call in function_calls:
                        if call.name == "search_workspace":
                            total_tool_calls += 1
                            query_arg = call.args.get("query")
                            if query_arg:
                                additional_results = await hybrid_search(db, query_arg, project_id, limit=limit)
                                add_results_to_citation_map(additional_results, citation_map, context_blocks)

                                tool_formatted = []
                                for res in additional_results:
                                    res_key = next((k for k, v in citation_map.items() if v["node_id"] == str(res.node_id)), "?")
                                    tool_formatted.append(f"[{res_key}] {res.title or 'Untitled'}: {res.content}")

                                tool_response_text = "\n\n".join(tool_formatted) or "No additional results found."
                                tool_parts.append(
                                    types.Part.from_function_response(
                                        name=call.name,
                                        response={"result": tool_response_text}
                                    )
                                )

                    messages.append(
                        types.Content(
                            role="tool",
                            parts=tool_parts
                        )
                    )
                    loop_count += 1

            metrics.agentic_loop_latency_s = round(time.perf_counter() - t0, 4)
            metrics.agentic_tool_calls = total_tool_calls
            metrics.agentic_loop_iterations = loop_count
            logger.info(
                f"[RAG] Agentic loop: {metrics.agentic_loop_latency_s}s | "
                f"{loop_count} iterations | {total_tool_calls} tool calls"
            )

            # ── 10. Final Generation with JSON Schema ─────────────────────
            t0 = time.perf_counter()
            formatted_context_final = "\n\n".join(context_blocks)
            final_prompt = (
                f"Generate the final structured response matching the ChatResponse schema.\n"
                f"Use the accumulated context resources below.\n"
                f"--- FINAL CONTEXT RESOURCES ---\n"
                f"{formatted_context_final}\n\n"
                f"Ensure inline markdown citations (like [1], [2]) are present in the 'answer' field and correlate exactly with the 'citations' array. "
                f"Provide a realistic confidence_score (0.0 to 1.0)."
            )

            messages.append(
                types.Content(
                    role="user",
                    parts=[types.Part.from_text(text=final_prompt)]
                )
            )

            try:
                async with trace.span("generation"):
                    response = await generate_content_with_retry(
                        client=client,
                        model=model_name,
                        contents=messages,
                        config=types.GenerateContentConfig(
                            response_mime_type="application/json",
                            response_schema=ChatResponse,
                            temperature=0.1
                        )
                    )

                chat_res = ChatResponse.model_validate_json(response.text)

                # Supplement citations with citation_map data
                active_citations = []
                for citation in chat_res.citations:
                    citation_key_str = str(citation.key)
                    if citation_key_str in citation_map:
                        ref = citation_map[citation_key_str]
                        citation.node_type = ref["node_type"]
                        citation.title = ref["title"]
                        citation.url = ref["url"]
                        citation.snippet = ref["snippet"]
                    active_citations.append(citation)
                chat_res.citations = active_citations

                metrics.generation_latency_s = round(time.perf_counter() - t0, 4)
                metrics.total_latency_s = round(time.perf_counter() - pipeline_start, 4)
                metrics.confidence_score = chat_res.confidence_score
                metrics.citation_count = len(active_citations)
                metrics.context_sources_used = len(citation_map)
                metrics.answer_length_chars = len(chat_res.answer)
                metrics.context_length_chars = len(formatted_context_final)
                metrics.context_utilization_ratio = (
                    round(metrics.citation_count / metrics.context_sources_used, 4)
                    if metrics.context_sources_used > 0 else 0.0
                )

                logger.info(
                    f"[RAG] Generation: {metrics.generation_latency_s}s | "
                    f"Total: {metrics.total_latency_s}s | "
                    f"Confidence: {metrics.confidence_score} | "
                    f"Citations: {metrics.citation_count}/{metrics.context_sources_used}"
                )

                # Save turns in history
                history.append({"role": "user", "content": query})
                history.append({"role": "model", "content": chat_res.answer})

                # ── 11. RAGAS Evaluation (fire-and-forget async) ──────────
                if settings.ragas_enabled:
                    raw_contexts = [r.content for r in reranked_results if r.content]
                    asyncio.create_task(
                        _run_ragas_and_update_metrics(
                            query=query,
                            answer=chat_res.answer,
                            contexts=raw_contexts,
                            metrics=metrics,
                            trace=trace,
                        )
                    )

                # Attach final outputs to LangSmith trace
                trace.set_outputs({
                    "confidence_score": metrics.confidence_score,
                    "citation_count": metrics.citation_count,
                    "total_latency_s": metrics.total_latency_s,
                })

                return chat_res, metrics

            except Exception as e:
                logger.exception(f"Gemini Chat / RAG final generation failed: {e}")
                metrics.total_latency_s = round(time.perf_counter() - pipeline_start, 4)
                metrics.generation_latency_s = round(time.perf_counter() - t0, 4)
                return ChatResponse(
                    answer="I encountered an unexpected error while generating the alignment response. Please try again shortly.",
                    confidence_score=0.0,
                    citations=[]
                ), metrics


async def _run_ragas_and_update_metrics(
    query: str,
    answer: str,
    contexts: List[str],
    metrics: RAGMetrics,
    trace: Any,
) -> None:
    """
    Fire-and-forget coroutine: runs RAGAS evaluation and patches metrics + trace.
    Called via asyncio.create_task() so it does not block the response.
    """
    from app.services.evaluation import compute_ragas_metrics

    try:
        async with trace.span("ragas_evaluation"):
            ragas = await compute_ragas_metrics(
                query=query,
                answer=answer,
                contexts=contexts,
            )

        metrics.ragas_faithfulness = ragas.faithfulness
        metrics.ragas_answer_relevancy = ragas.answer_relevancy
        metrics.ragas_context_precision = ragas.context_precision
        metrics.ragas_context_recall = ragas.context_recall
        metrics.ragas_context_entity_recall = ragas.context_entity_recall
        metrics.ragas_score = ragas.ragas_score
        metrics.ragas_evaluated = ragas.evaluated
        metrics.ragas_error = ragas.error

        trace.set_ragas_scores(ragas)

        logger.info(
            f"[RAGAS] Complete | Score={ragas.ragas_score:.3f} | "
            f"Faithfulness={ragas.faithfulness:.3f} | "
            f"AnswerRelevancy={ragas.answer_relevancy:.3f} | "
            f"ContextPrecision={ragas.context_precision:.3f}"
        )
    except Exception as e:
        logger.warning(f"[RAGAS] Background evaluation failed: {e}")
        metrics.ragas_error = str(e)
