"""
Conversational AI Chat & RAG Service with Citations and Confidence Scoring.
"""

import uuid
import logging
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from google import genai
from google.genai import types

from app.config import settings
from app.services.search import hybrid_search

logger = logging.getLogger(__name__)

class ChatCitation(BaseModel):
    """Citation mapping a statement back to a source node in the Feature Intelligence Graph."""
    key: int = Field(description="The numeric citation key, e.g., 1 (for [1]).")
    node_id: str = Field(description="The UUID string of the cited node.")
    node_type: str = Field(description="The type of node (e.g. requirement, decision, event).")
    title: str = Field(description="The title or brief summary of the node.")
    url: Optional[str] = Field(None, description="External URL if available.")
    snippet: Optional[str] = Field(None, description="A brief matching text snippet from the node content.")


class ChatResponse(BaseModel):
    """The structured, validated response generated by the conversational AI agent."""
    answer: str = Field(description="The rich markdown response. Must cite sources inline using format [1], [2], matching the keys in the citations list.")
    confidence_score: float = Field(description="A confidence score between 0.0 and 1.0 reflecting factual alignment with the retrieved context.")
    citations: List[ChatCitation] = Field(description="List of exact nodes cited in the answer.")


# In-memory session store (session_id -> list of message dicts)
# Each message dict has: {"role": "user" | "model", "content": str}
chat_sessions: Dict[str, List[Dict[str, str]]] = {}


def get_or_create_session(session_id: str) -> List[Dict[str, str]]:
    """Retrieve or create a conversational history session."""
    if session_id not in chat_sessions:
        chat_sessions[session_id] = []
    return chat_sessions[session_id]


async def retrieve_and_generate(
    db,
    query: str,
    project_id: uuid.UUID,
    session_id: Optional[str] = None,
    limit: int = 5
) -> ChatResponse:
    """
    Executes RAG pipeline:
    1. Retrieval: Performs Reciprocal Rank Fusion hybrid search on Postgres & Qdrant.
    2. Context Formatting: Builds structured text context with explicit citation keys.
    3. LLM Generation: Sends history, prompt, and context to Google Gemini with Pydantic constraint schema.
    4. Session Update: Appends turns to history log.
    """
    # 1. Retrieval
    search_results = await hybrid_search(db, query, project_id, limit=limit)

    # Map retrieved results into citation reference list
    citation_map: Dict[str, Dict[str, Any]] = {}
    context_blocks = []
    
    for idx, res in enumerate(search_results, start=1):
        ref_key = idx
        node_id_str = str(res.node_id)
        
        # Build context prompt entry
        context_blocks.append(
            f"--- SOURCE [{ref_key}] ---\n"
            f"Node ID: {node_id_str}\n"
            f"Type: {res.node_type}\n"
            f"Title: {res.title or 'Untitled'}\n"
            f"Content: {res.content}\n"
            f"Metadata: {res.metadata or {}}\n"
            f"Graph Relationships: {res.graph_context or {}}\n"
        )
        
        # Store for response constructor mapping
        citation_map[str(ref_key)] = {
            "key": ref_key,
            "node_id": node_id_str,
            "node_type": res.node_type,
            "title": res.title or "Untitled",
            "url": res.metadata.get("url") if res.metadata else None,
            "snippet": res.content[:200] + "..." if len(res.content) > 200 else res.content
        }

    formatted_context = "\n\n".join(context_blocks)

    # 2. Conversation History
    actual_session_id = session_id or str(uuid.uuid4())
    history = get_or_create_session(actual_session_id)
    
    # Format history turns for the system instructions
    history_str = ""
    for turn in history:
        history_str += f"{turn['role'].capitalize()}: {turn['content']}\n"

    # 3. Prompt Engineering
    system_instruction = (
        "You are Axis AI, a premium software engineering alignment assistant.\n"
        "Your objective is to provide extremely accurate, well-reasoned answers to help teams understand their requirements, decisions, stakeholder actions, and development event logs.\n\n"
        "Instructions:\n"
        "1. Answer the User Query using the provided SOURCE blocks below.\n"
        "2. You MUST cite your statements inline using exact keys like [1], [2], etc., matching the respective SOURCE entry.\n"
        "3. Only cite facts that are directly supported by the sources. Do not invent citations or make claims without source evidence.\n"
        "4. If the sources do not contain enough information to answer, state clearly that you cannot find the answer in the workspace resources.\n"
        "5. Provide a realistic confidence_score (0.0 to 1.0) indicating how fated/aligned your answer is with the retrieved sources.\n"
    )

    full_prompt = (
        f"{system_instruction}\n"
        f"--- CONTEXT RESOURCES ---\n"
        f"{formatted_context}\n\n"
        f"--- CONVERSATION HISTORY ---\n"
        f"{history_str}\n"
        f"User Query: {query}\n\n"
        f"Generate a beautiful, formatted response matching the specified JSON schema."
    )

    # 4. Generate with Gemini
    api_key = settings.gemini_api_key
    client = genai.Client(api_key=api_key)
    
    try:
        response = await client.aio.models.generate_content(
            model=settings.llm_model,
            contents=full_prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=ChatResponse,
                temperature=0.2
            )
        )
        
        # Validate output against Pydantic schema
        chat_res = ChatResponse.model_validate_json(response.text)
        
        # Supplement citations in case the LLM did not fill matching keys correctly
        # Filter citations to only return those that are actually referenced in the answer
        active_citations = []
        for citation in chat_res.citations:
            citation_key_str = str(citation.key)
            if citation_key_str in citation_map:
                ref = citation_map[citation_key_str]
                citation.node_type = ref["node_type"]
                citation.title = ref["title"]
                citation.url = ref["url"]
                citation.snippet = ref["snippet"]
            active_citations.append(citation)
            
        chat_res.citations = active_citations

        # Save turns in history
        history.append({"role": "user", "content": query})
        history.append({"role": "model", "content": chat_res.answer})
        
        return chat_res
        
    except Exception as e:
        logger.exception(f"Gemini Chat / RAG generation failed: {e}")
        # Fallback graceful schema in case of rate limits or errors
        return ChatResponse(
            answer="I encountered an unexpected error while generating the alignment response. Please try again shortly.",
            confidence_score=0.0,
            citations=[]
        )
